"""database bonak

Revision ID: 452adea197ea
Revises: eb7271ea3d2f
Create Date: 2024-11-30 01:18:21.973114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452adea197ea'
down_revision = 'eb7271ea3d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_by', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_tguide_date', ['tguide_id', 'availability_date'])
        batch_op.create_foreign_key(None, 'Users', ['booked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_tguide_date', type_='unique')
        batch_op.drop_column('booked_by')

    # ### end Alembic commands ###
