"""LCascade

Revision ID: 49dbbed7da96
Revises: 62b41a8b92b2
Create Date: 2024-12-01 19:39:48.757810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49dbbed7da96'
down_revision = '62b41a8b92b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.drop_constraint('Availability_tguide_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tour_Guide', ['tguide_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('Booking_tour_guide_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tour_Guide', ['tour_guide_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Characteristic', schema=None) as batch_op:
        batch_op.drop_constraint('Characteristic_tguide_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tour_Guide', ['tguide_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Skill', schema=None) as batch_op:
        batch_op.drop_constraint('Skill_tguide_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tour_Guide', ['tguide_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Skill_tguide_id_fkey', 'Tour_Guide', ['tguide_id'], ['id'])

    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Characteristic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Characteristic_tguide_id_fkey', 'Tour_Guide', ['tguide_id'], ['id'])

    with op.batch_alter_table('Booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Booking_tour_guide_id_fkey', 'Tour_Guide', ['tour_guide_id'], ['id'])
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Availability_tguide_id_fkey', 'Tour_Guide', ['tguide_id'], ['id'])

    # ### end Alembic commands ###
