"""Acc Stat

Revision ID: 5e72c3646643
Revises: 452adea197ea
Create Date: 2024-11-30 23:52:39.520768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e72c3646643'
down_revision = '452adea197ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tour_Guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tp_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('tp_active')

    with op.batch_alter_table('Tour_Guide', schema=None) as batch_op:
        batch_op.drop_column('account_status')

    # ### end Alembic commands ###
