"""Acc Stat4

Revision ID: 62b41a8b92b2
Revises: 5e72c3646643
Create Date: 2024-12-01 01:03:09.370589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b41a8b92b2'
down_revision = '5e72c3646643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tour_Operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tp_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('tp_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tp_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Tour_Operator', schema=None) as batch_op:
        batch_op.drop_column('tp_active')

    # ### end Alembic commands ###
