"""notif

Revision ID: 7c46352a5802
Revises: a22e697e7bbf
Create Date: 2024-11-24 14:37:45.436502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c46352a5802'
down_revision = 'a22e697e7bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tguide_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_notification_tguide_id', ['tguide_id'], unique=False)
        batch_op.create_foreign_key(None, 'Tour_Guide', ['tguide_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_notification_tguide_id')
        batch_op.drop_column('tguide_id')

    # ### end Alembic commands ###
