"""RR Book_id

Revision ID: 91db3b6565b7
Revises: 
Create Date: 2024-11-22 14:20:07.407941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91db3b6565b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reviews_Rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_reviews_rating_booking_id', ['booking_id'], unique=False)
        batch_op.create_foreign_key(None, 'Booking', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reviews_Rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_reviews_rating_booking_id')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
