"""Update Notification model relationships

Revision ID: a22e697e7bbf
Revises: 
Create Date: 2024-11-24 12:55:57.752769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22e697e7bbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=False))
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('idx_notification_tguide_id')
        batch_op.create_index('idx_notification_user_id', ['user_id'], unique=False)
        batch_op.drop_constraint('Notification_tguide_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'])
        batch_op.drop_column('tguide_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tguide_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Notification_tguide_id_fkey', 'Tour_Guide', ['tguide_id'], ['id'])
        batch_op.drop_index('idx_notification_user_id')
        batch_op.create_index('idx_notification_tguide_id', ['tguide_id'], unique=False)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('message')
        batch_op.drop_column('role')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
