"""notif back

Revision ID: eb7271ea3d2f
Revises: 7c46352a5802
Create Date: 2024-11-24 17:52:09.750411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7271ea3d2f'
down_revision = '7c46352a5802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_tguide_id')
        batch_op.drop_constraint('Notification_tguide_id_fkey', type_='foreignkey')
        batch_op.drop_column('tguide_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tguide_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Notification_tguide_id_fkey', 'Tour_Guide', ['tguide_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_notification_tguide_id', ['tguide_id'], unique=False)

    # ### end Alembic commands ###
